services:
  postgres:
    image: postgres:latest
    container_name: clbio-db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - clbio-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: clbio-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file:
      - .env
    networks:
      - clbio-net

  clbio-api:
    build:
      context: .
      dockerfile: Clbio.API/Dockerfile
    container_name: clbio-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_DOCKER}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - clbio-net

volumes:
  postgres-data:

networks:
  clbio-net:
    driver: bridge
